spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cafe?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul
    username: cafeuser
    password: cafepw


  jpa:
    hibernate:
      ddl-auto: update          # dev 단계 – 엔티티 정의대로 테이블 자동 반영
    properties:
      hibernate:
        format_sql: true
        show_sql: true
