spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cafe?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul
    username: cafeuser
    password: cafepw

  jpa:
    hibernate:
      ddl-auto: update
      temp:
        use_jdbc_metadata_defaults: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

